import {auth} from "@/auth";import {prisma} from "@/lib/prisma";import {notFound,redirect} from "next/navigation";import Link from "next/link";import {ArrowLeft,ArrowUpRight,CalendarDays,CheckCircle2,Clock3,FileText,Gift,MapPin,UserRound} from "lucide-react";import MobileNav from "@/components/layout/MobileNav";import ApplicationStatusControl from "@/components/workflow/ApplicationStatusControl";import ApplicationWithdrawButton from "@/components/applications/ApplicationWithdrawButton";
const stages=["APPLIED","SHORTLISTED","APTITUDE","TECHNICAL","HR","SELECTED","OFFERED","ACCEPTED"];
const label=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const fmt=(v:Date|null|undefined)=>v?new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(v):"Not scheduled";
export default async function ApplicationDetails({params}:{params:Promise<{id:string}>}){
 const session=await auth();if(!session?.user?.email)redirect("/login");const {id}=await params;const user=await prisma.user.findUnique({where:{email:session.user.email},select:{id:true,role:true}});if(!user)redirect("/login");
 const a=await prisma.application.findUnique({where:{id},include:{student:{include:{user:true}},drive:{include:{company:true}},interviews:{orderBy:{scheduledAt:"asc"}},offer:true}});if(!a)notFound();
 const staff=user.role==="ADMIN"||user.role==="PLACEMENT_OFFICER",owner=a.student.userId===user.id;if(!staff&&!owner)redirect("/applications");
 const idx=stages.indexOf(a.status),canWithdraw=owner&&!['WITHDRAWN','ACCEPTED','REJECTED'].includes(a.status);
 const timeline=[{date:a.appliedAt,type:"APPLICATION",title:"Application submitted",text:`Applied for ${a.drive.role} at ${a.drive.company.name}.`,icon:FileText},...a.interviews.map(i=>({date:i.scheduledAt||i.createdAt,type:"INTERVIEW",title:`${i.round} interview`,text:`${i.mode}${i.result?` · Result: ${label(i.result)}`:" · Result pending"}`,icon:CalendarDays})),...(a.offer?[{date:a.offer.createdAt,type:"OFFER",title:"Offer created",text:`${a.offer.packageLpa?`₹${a.offer.packageLpa} LPA`:"Package not specified"}${a.offer.joiningDate?` · Joining ${fmt(a.offer.joiningDate)}`:""}`,icon:Gift}]:[])].sort((x,y)=>y.date.getTime()-x.date.getTime());
 return <main className="dashboard"><aside className="sidebar"><div className="brand"><div className="logo small">P</div><div><b>PlacementCRM</b><small>Placement workspace</small></div></div><div className="sidebar-section-label">APPLICATION WORKSPACE</div><nav><Link className="nav-item" href="/dashboard">Dashboard</Link><Link className="nav-item" href="/opportunities">Opportunities</Link><Link className="nav-item active" href={staff?"/applications":"/my-applications"}>Applications</Link><Link className="nav-item" href="/interview-hub">Interviews</Link><Link className="nav-item" href="/offer-center">Offers</Link><Link className="nav-item" href="/notifications">Notifications</Link></nav><div className="sidebar-bottom"><span className="role-pill">{user.role}</span><small>Google authentication enabled</small></div></aside>
 <section className="content"><header className="topbar page-topbar"><div><p className="eyebrow">APPLICATION DETAIL</p><h1>{a.drive.role}</h1><p>{a.drive.company.name} · {a.drive.location||"Location not specified"}</p></div><Link className="secondary" href={staff?"/applications":"/my-applications"}><ArrowLeft size={15}/> Back</Link></header>
 <div className="application-detail-grid"><section className="panel application-summary-card"><div className="application-summary-head"><div className="company-avatar large">{a.drive.company.name.charAt(0).toUpperCase()}</div><div><p className="eyebrow">{a.drive.company.name}</p><h2>{a.drive.role}</h2><span>{a.drive.packageLpa?`₹${a.drive.packageLpa} LPA`:"Package not specified"} · {a.drive.location||"Location not specified"}</span></div><span className={`status-badge status-${a.status.toLowerCase()}`}>{label(a.status)}</span></div><div className="application-detail-meta"><div><CalendarDays size={15}/><span>Applied<strong>{fmt(a.appliedAt)}</strong></span></div><div><MapPin size={15}/><span>Drive date<strong>{fmt(a.drive.driveDate)}</strong></span></div><div><Clock3 size={15}/><span>Deadline<strong>{fmt(a.drive.applicationDeadline)}</strong></span></div></div>{!['REJECTED','WITHDRAWN','ACCEPTED'].includes(a.status)&&<div className="application-progress">{stages.map((s,i)=><div key={s} className={`application-progress-stage ${i<=idx?"done":""} ${s===a.status?"current":""}`}><span>{i<idx?<CheckCircle2 size={12}/>:i===idx?<span className="progress-dot"/>:null}</span><small>{label(s)}</small></div>)}</div>}{staff&&<div className="application-actions"><ApplicationStatusControl id={a.id} current={a.status} canManage={staff}/></div>}{canWithdraw&&<div className="application-actions"><ApplicationWithdrawButton applicationId={a.id}/></div>}</section>
 {staff&&<section className="panel application-candidate-card"><div className="section-title"><UserRound size={17}/><div><h2>Candidate</h2><p>Student linked to this application</p></div></div><div className="candidate-detail"><strong>{a.student.user.name||"Unnamed student"}</strong><span>{a.student.usn||"USN not set"}</span><span>{a.student.department||"Department not set"} · CGPA {a.student.cgpa??"—"}</span><Link className="secondary" href={`/students/${a.student.id}`}>View profile <ArrowUpRight size={14}/></Link></div></section>}</div>
 <div className="application-detail-columns"><section className="panel"><div className="section-title"><Clock3 size={17}/><div><h2>Application timeline</h2><p>Key events recorded for this application.</p></div></div><div className="application-timeline">{timeline.map((item,i)=>{const Icon=item.icon;return <div className="application-timeline-item" key={`${item.type}-${i}`}><div className="timeline-icon"><Icon size={15}/></div><div><span>{item.type}</span><h3>{item.title}</h3><p>{item.text}</p><small>{fmt(item.date)}</small></div></div>})}</div></section><section className="panel"><div className="section-title"><CalendarDays size={17}/><div><h2>Interviews</h2><p>Scheduled rounds and results.</p></div></div>{a.interviews.length?<div className="detail-list">{a.interviews.map(i=><div className="detail-list-row" key={i.id}><div><strong>{i.round}</strong><span>{fmt(i.scheduledAt)} · {i.mode}</span></div><b>{i.result?label(i.result):"Pending"}</b></div>)}</div>:<div className="detail-empty">No interview rounds scheduled yet.</div>}{a.offer&&<div className="offer-summary-box"><Gift size={17}/><div><strong>Offer: {label(a.offer.status)}</strong><span>{a.offer.packageLpa?`₹${a.offer.packageLpa} LPA`:"Package not specified"}{a.offer.joiningDate?` · Joining ${fmt(a.offer.joiningDate)}`:""}</span></div><Link className="secondary" href="/offer-center">View offers</Link></div>}</section></div>
 </section></main>;
}
